// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pxdl

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel6, 102);
    lv_obj_set_height(ui_Panel6, 445);
    lv_obj_set_x(ui_Panel6, 9);
    lv_obj_set_y(ui_Panel6, 17);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderRPMControl = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_SliderRPMControl, 0, 90);
    lv_obj_set_width(ui_SliderRPMControl, 43);
    lv_obj_set_height(ui_SliderRPMControl, 350);
    lv_obj_set_x(ui_SliderRPMControl, -336);
    lv_obj_set_y(ui_SliderRPMControl, -29);
    lv_obj_set_align(ui_SliderRPMControl, LV_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_SliderRPMControl, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderRPMControl, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderRPMControl, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderRPMControl, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lablethrottle = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_lablethrottle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lablethrottle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lablethrottle, -335);
    lv_obj_set_y(ui_lablethrottle, 195);
    lv_obj_set_align(ui_lablethrottle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lablethrottle, "Throttle");

    ui_IGPANNEL2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_IGPANNEL2, 350);
    lv_obj_set_height(ui_IGPANNEL2, 104);
    lv_obj_set_x(ui_IGPANNEL2, -13);
    lv_obj_set_y(ui_IGPANNEL2, 23);
    lv_obj_set_align(ui_IGPANNEL2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_IGPANNEL2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGPANNEL2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGPANNEL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_IGPANNEL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_IGPANNEL2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IGPANNEL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IGPANNEL2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGPANNEL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGNITION2 = lv_obj_create(ui_IGPANNEL2);
    lv_obj_set_width(ui_IGNITION2, lv_pct(50));
    lv_obj_set_height(ui_IGNITION2, lv_pct(100));
    lv_obj_set_align(ui_IGNITION2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_IGNITION2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGNITION2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGNITION2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGNITION2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGNITION2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGNITION2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGNITION2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGNITION2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_label_create(ui_IGNITION2);
    lv_obj_set_width(ui_RPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RPM, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RPM, "RPM");
    lv_label_set_recolor(ui_RPM, "true");
    lv_obj_set_style_text_color(ui_RPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lablevalueprm = lv_label_create(ui_IGNITION2);
    lv_obj_set_width(ui_Lablevalueprm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lablevalueprm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lablevalueprm, 60);
    lv_obj_set_y(ui_Lablevalueprm, 10);
    lv_obj_set_align(ui_Lablevalueprm, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lablevalueprm, "110");
    lv_obj_set_style_text_color(ui_Lablevalueprm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lablevalueprm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lablevalueprm, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME2 = lv_obj_create(ui_IGPANNEL2);
    lv_obj_set_width(ui_TIME2, lv_pct(50));
    lv_obj_set_height(ui_TIME2, lv_pct(100));
    lv_obj_set_align(ui_TIME2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_TIME2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TIME2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TIME2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TIME2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TIME2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TIME2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TIME2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TIME2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Throttle = lv_label_create(ui_TIME2);
    lv_obj_set_width(ui_Throttle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Throttle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Throttle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Throttle, "Throttle Pos");
    lv_obj_set_style_text_color(ui_Throttle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Throttle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Throttle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableTHRPosition = lv_label_create(ui_TIME2);
    lv_obj_set_width(ui_LableTHRPosition, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableTHRPosition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableTHRPosition, 60);
    lv_obj_set_y(ui_LableTHRPosition, 10);
    lv_obj_set_align(ui_LableTHRPosition, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableTHRPosition, "110°");
    lv_obj_set_style_text_color(ui_LableTHRPosition, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableTHRPosition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableTHRPosition, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_IGPANNEL2);
    lv_obj_set_width(ui_Panel2, 2);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGPANNEL1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_IGPANNEL1, 350);
    lv_obj_set_height(ui_IGPANNEL1, 104);
    lv_obj_set_x(ui_IGPANNEL1, -11);
    lv_obj_set_y(ui_IGPANNEL1, 141);
    lv_obj_set_align(ui_IGPANNEL1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_IGPANNEL1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGPANNEL1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGPANNEL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_IGPANNEL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_IGPANNEL1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IGPANNEL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IGPANNEL1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGPANNEL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGNITION1 = lv_obj_create(ui_IGPANNEL1);
    lv_obj_set_width(ui_IGNITION1, lv_pct(50));
    lv_obj_set_height(ui_IGNITION1, lv_pct(100));
    lv_obj_set_align(ui_IGNITION1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_IGNITION1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGNITION1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGNITION1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGNITION1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGNITION1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGNITION1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGNITION1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGNITION1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lableMapIat = lv_label_create(ui_IGNITION1);
    lv_obj_set_width(ui_lableMapIat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableMapIat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lableMapIat, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lableMapIat, "Map + IAT");
    lv_label_set_recolor(ui_lableMapIat, "true");
    lv_obj_set_style_text_color(ui_lableMapIat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lableMapIat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lableMapIat, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle1 = lv_label_create(ui_IGNITION1);
    lv_obj_set_width(ui_LableAngle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle1, 60);
    lv_obj_set_y(ui_LableAngle1, 10);
    lv_obj_set_align(ui_LableAngle1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle1, "110");
    lv_obj_set_style_text_color(ui_LableAngle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableOxy = lv_obj_create(ui_IGPANNEL1);
    lv_obj_set_width(ui_LableOxy, lv_pct(50));
    lv_obj_set_height(ui_LableOxy, lv_pct(100));
    lv_obj_set_align(ui_LableOxy, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_LableOxy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LableOxy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LableOxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LableOxy, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LableOxy, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LableOxy, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LableOxy, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LableOxy, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_LableOxy);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "Oxy");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle2 = lv_label_create(ui_LableOxy);
    lv_obj_set_width(ui_LableAngle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle2, 60);
    lv_obj_set_y(ui_LableAngle2, 10);
    lv_obj_set_align(ui_LableAngle2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle2, "5us");
    lv_obj_set_style_text_color(ui_LableAngle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_IGPANNEL1);
    lv_obj_set_width(ui_Panel1, 2);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGPANNEL3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_IGPANNEL3, 350);
    lv_obj_set_height(ui_IGPANNEL3, 104);
    lv_obj_set_x(ui_IGPANNEL3, -10);
    lv_obj_set_y(ui_IGPANNEL3, 259);
    lv_obj_set_align(ui_IGPANNEL3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_IGPANNEL3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGPANNEL3, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGPANNEL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_IGPANNEL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_IGPANNEL3, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IGPANNEL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IGPANNEL3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGPANNEL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGNITION3 = lv_obj_create(ui_IGPANNEL3);
    lv_obj_set_width(ui_IGNITION3, lv_pct(50));
    lv_obj_set_height(ui_IGNITION3, lv_pct(100));
    lv_obj_set_align(ui_IGNITION3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_IGNITION3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGNITION3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGNITION3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGNITION3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGNITION3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGNITION3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGNITION3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGNITION3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableWaterTemp = lv_label_create(ui_IGNITION3);
    lv_obj_set_width(ui_LableWaterTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableWaterTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LableWaterTemp, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LableWaterTemp, "Water Temp");
    lv_label_set_recolor(ui_LableWaterTemp, "true");
    lv_obj_set_style_text_color(ui_LableWaterTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableWaterTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableWaterTemp, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle5 = lv_label_create(ui_IGNITION3);
    lv_obj_set_width(ui_LableAngle5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle5, 60);
    lv_obj_set_y(ui_LableAngle5, 10);
    lv_obj_set_align(ui_LableAngle5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle5, "110°");
    lv_obj_set_style_text_color(ui_LableAngle5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME3 = lv_obj_create(ui_IGPANNEL3);
    lv_obj_set_width(ui_TIME3, lv_pct(50));
    lv_obj_set_height(ui_TIME3, lv_pct(100));
    lv_obj_set_align(ui_TIME3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_TIME3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TIME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TIME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TIME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TIME3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TIME3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TIME3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TIME3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableKnk = lv_label_create(ui_TIME3);
    lv_obj_set_width(ui_LableKnk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableKnk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LableKnk, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LableKnk, "Knk");
    lv_obj_set_style_text_color(ui_LableKnk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableKnk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableKnk, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle6 = lv_label_create(ui_TIME3);
    lv_obj_set_width(ui_LableAngle6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle6, 60);
    lv_obj_set_y(ui_LableAngle6, 10);
    lv_obj_set_align(ui_LableAngle6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle6, "Nomal");
    lv_obj_set_style_text_color(ui_LableAngle6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_IGPANNEL3);
    lv_obj_set_width(ui_Panel3, 2);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonWelcome1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonWelcome1, 345);
    lv_obj_set_height(ui_ButtonWelcome1, 85);
    lv_obj_set_x(ui_ButtonWelcome1, 216);
    lv_obj_set_y(ui_ButtonWelcome1, -14);
    lv_obj_set_align(ui_ButtonWelcome1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonWelcome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWelcome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lableButton1 = lv_label_create(ui_ButtonWelcome1);
    lv_obj_set_width(ui_lableButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableButton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lableButton1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableButton1, "Get started!");
    lv_obj_set_style_text_font(ui_lableButton1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGPANNEL4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_IGPANNEL4, 302);
    lv_obj_set_height(ui_IGPANNEL4, 335);
    lv_obj_set_x(ui_IGPANNEL4, -377);
    lv_obj_set_y(ui_IGPANNEL4, 21);
    lv_obj_set_align(ui_IGPANNEL4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_IGPANNEL4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGPANNEL4, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGPANNEL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_IGPANNEL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_IGPANNEL4, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IGPANNEL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IGPANNEL4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGPANNEL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGNITION4 = lv_obj_create(ui_IGPANNEL4);
    lv_obj_set_width(ui_IGNITION4, lv_pct(50));
    lv_obj_set_height(ui_IGNITION4, lv_pct(49));
    lv_obj_clear_flag(ui_IGNITION4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGNITION4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGNITION4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGNITION4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGNITION4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGNITION4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGNITION4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGNITION4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableIg = lv_label_create(ui_IGNITION4);
    lv_obj_set_width(ui_LableIg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableIg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LableIg, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LableIg, "IGN ANGLE");
    lv_label_set_recolor(ui_LableIg, "true");
    lv_obj_set_style_text_color(ui_LableIg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableIg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableIg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle7 = lv_label_create(ui_IGNITION4);
    lv_obj_set_width(ui_LableAngle7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle7, 60);
    lv_obj_set_y(ui_LableAngle7, 10);
    lv_obj_set_align(ui_LableAngle7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle7, "110°");
    lv_obj_set_style_text_color(ui_LableAngle7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle7, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME4 = lv_obj_create(ui_IGPANNEL4);
    lv_obj_set_width(ui_TIME4, lv_pct(49));
    lv_obj_set_height(ui_TIME4, lv_pct(49));
    lv_obj_set_x(ui_TIME4, 0);
    lv_obj_set_y(ui_TIME4, 3);
    lv_obj_set_align(ui_TIME4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TIME4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TIME4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TIME4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TIME4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TIME4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TIME4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TIME4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TIME4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lablinj = lv_label_create(ui_TIME4);
    lv_obj_set_width(ui_lablinj, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lablinj, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lablinj, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lablinj, "INJ ANGLE");
    lv_obj_set_style_text_color(ui_lablinj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lablinj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lablinj, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle8 = lv_label_create(ui_TIME4);
    lv_obj_set_width(ui_LableAngle8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle8, 60);
    lv_obj_set_y(ui_LableAngle8, 10);
    lv_obj_set_align(ui_LableAngle8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle8, "110°");
    lv_obj_set_style_text_color(ui_LableAngle8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_IGPANNEL4);
    lv_obj_set_width(ui_Panel4, 2);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IGNITION5 = lv_obj_create(ui_IGPANNEL4);
    lv_obj_set_width(ui_IGNITION5, lv_pct(50));
    lv_obj_set_height(ui_IGNITION5, lv_pct(49));
    lv_obj_set_x(ui_IGNITION5, 0);
    lv_obj_set_y(ui_IGNITION5, -3);
    lv_obj_set_align(ui_IGNITION5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_IGNITION5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IGNITION5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IGNITION5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IGNITION5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IGNITION5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IGNITION5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IGNITION5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IGNITION5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM2 = lv_label_create(ui_IGNITION5);
    lv_obj_set_width(ui_RPM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RPM2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RPM2, "WIDTH");
    lv_label_set_recolor(ui_RPM2, "true");
    lv_obj_set_style_text_color(ui_RPM2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle9 = lv_label_create(ui_IGNITION5);
    lv_obj_set_width(ui_LableAngle9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle9, 60);
    lv_obj_set_y(ui_LableAngle9, 10);
    lv_obj_set_align(ui_LableAngle9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle9, "1 ns");
    lv_obj_set_style_text_color(ui_LableAngle9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle9, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TIME5 = lv_obj_create(ui_IGPANNEL4);
    lv_obj_set_width(ui_TIME5, lv_pct(49));
    lv_obj_set_height(ui_TIME5, lv_pct(49));
    lv_obj_set_x(ui_TIME5, 3);
    lv_obj_set_y(ui_TIME5, -2);
    lv_obj_set_align(ui_TIME5, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_TIME5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TIME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TIME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TIME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TIME5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TIME5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TIME5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TIME5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Throttle2 = lv_label_create(ui_TIME5);
    lv_obj_set_width(ui_Throttle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Throttle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Throttle2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Throttle2, "WIDTH");
    lv_obj_set_style_text_color(ui_Throttle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Throttle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Throttle2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableAngle10 = lv_label_create(ui_TIME5);
    lv_obj_set_width(ui_LableAngle10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LableAngle10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LableAngle10, 60);
    lv_obj_set_y(ui_LableAngle10, 10);
    lv_obj_set_align(ui_LableAngle10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LableAngle10, "1 ns");
    lv_obj_set_style_text_color(ui_LableAngle10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableAngle10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableAngle10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SliderRPMControl, ui_event_SliderRPMControl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWelcome1, ui_event_ButtonWelcome1, LV_EVENT_ALL, NULL);

}
