// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pxdl

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonWelcome = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonWelcome, 488);
    lv_obj_set_height(ui_ButtonWelcome, 85);
    lv_obj_set_x(ui_ButtonWelcome, 0);
    lv_obj_set_y(ui_ButtonWelcome, -70);
    lv_obj_set_align(ui_ButtonWelcome, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ButtonWelcome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWelcome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lableButton = lv_label_create(ui_ButtonWelcome);
    lv_obj_set_width(ui_lableButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lableButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lableButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lableButton, "Get started!");
    lv_obj_set_style_text_font(ui_lableButton, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 8);
    lv_obj_set_y(ui_Label1, -141);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "WELCOM TO HBHANOI");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonWelcome, ui_event_ButtonWelcome, LV_EVENT_ALL, NULL);

}
