// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pxdl

#ifndef _PXDL_UI_H
#define _PXDL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_ButtonWelcome(lv_event_t * e);
extern lv_obj_t * ui_ButtonWelcome;
extern lv_obj_t * ui_lableButton;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel6;
void ui_event_SliderRPMControl(lv_event_t * e);
extern lv_obj_t * ui_SliderRPMControl;
extern lv_obj_t * ui_lablethrottle;
extern lv_obj_t * ui_IGPANNEL2;
extern lv_obj_t * ui_IGNITION2;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_Lablevalueprm;
extern lv_obj_t * ui_TIME2;
extern lv_obj_t * ui_Throttle;
extern lv_obj_t * ui_LableTHRPosition;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_IGPANNEL1;
extern lv_obj_t * ui_IGNITION1;
extern lv_obj_t * ui_lableMapIat;
extern lv_obj_t * ui_LableAngle1;
extern lv_obj_t * ui_LableOxy;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LableAngle2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_IGPANNEL3;
extern lv_obj_t * ui_IGNITION3;
extern lv_obj_t * ui_LableWaterTemp;
extern lv_obj_t * ui_LableAngle5;
extern lv_obj_t * ui_TIME3;
extern lv_obj_t * ui_LableKnk;
extern lv_obj_t * ui_LableAngle6;
extern lv_obj_t * ui_Panel3;
void ui_event_ButtonWelcome1(lv_event_t * e);
extern lv_obj_t * ui_ButtonWelcome1;
extern lv_obj_t * ui_lableButton1;
extern lv_obj_t * ui_IGPANNEL4;
extern lv_obj_t * ui_IGNITION4;
extern lv_obj_t * ui_LableIg;
extern lv_obj_t * ui_LableAngle7;
extern lv_obj_t * ui_TIME4;
extern lv_obj_t * ui_lablinj;
extern lv_obj_t * ui_LableAngle8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_IGNITION5;
extern lv_obj_t * ui_RPM2;
extern lv_obj_t * ui_LableAngle9;
extern lv_obj_t * ui_TIME5;
extern lv_obj_t * ui_Throttle2;
extern lv_obj_t * ui_LableAngle10;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_audio_wave_1_png);    // assets\audio_wave_1.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
