// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: pxdl

#include "ui.h"
#include "main.h"
#include <stdio.h>
#include "../../SPI_Device_res/Mcp4xxx.h"
void ChangeRPM(lv_event_t * e)
{
	// Your code here
	//hello
	uint32_t slider_value ;
	uint32_t Rpm_value ;

	 lv_obj_t * target = lv_event_get_target(e);
	slider_value = lv_slider_get_value(target);// slider_value 0 -> 90
	Rpm_value = 30 * slider_value + 800;

	// speed 15-> 3500
	// change value ARR with timer 1mhz
	//
	//
	static char buf[5]; /* max 3 bytes for number plus 1 null terminating byte */
	        snprintf(buf, 5, "%u", Rpm_value);
	lv_label_set_text(ui_Lablevalueprm, buf); // change rpm in screen



	CKP_TIMER.Instance->ARR = 714285 / Rpm_value; // change rpm real
	CHANGE_TPS_REGISTER(slider_value);
	//HAL_UART_Transmit(&, (uint8_t*)data, strlen(data), HAL_MAX_DELAY);

}

void ChangeThrottle(lv_event_t * e)
{
	// Your code here
		uint32_t slider_value ;

		 lv_obj_t * target = lv_event_get_target(e);
		slider_value = lv_slider_get_value(target);// slider_value 0 -> 255
        MCP41_setWiper(slider_value, METER_1, 1);
}
